// lib/categories.ts

export type Category = {
  key: string;        // machine key used in data + URL
  label: string;      // human label shown in UI (exact as provided)
  options: { slug: string; label: string }[];
};

export const CATEGORIES: Category[] = [
  {
    key: "booking-channels",
    label: "Booking channels",
    options: [
      { slug: "website-widget", label: "Website widget" },
      { slug: "branded-microsite", label: "Branded microsite" },
      { slug: "ios-app", label: "iOS app" },
      { slug: "android-app", label: "Android app" },
      { slug: "facebook-instagram-booking", label: "Facebook/Instagram booking" },
      { slug: "google-reserve", label: "Google Reserve" },
      { slug: "phone-in-person-entry", label: "Phone / in-person entry" },
      { slug: "kiosk-self-service", label: "Kiosk / self-service" },
      { slug: "embedded-iframe", label: "Embedded iframe" },
      { slug: "custom-portal-via-api", label: "Custom portal via API" },
    ],
  },
  {
    key: "class-types",
    label: "Class types",
    options: [
      { slug: "drop-in-single-session", label: "Drop-in / single session" },
      { slug: "course-multi-session-series", label: "Course / multi-session series" },
      { slug: "workshops-events", label: "Workshops / events" },
      { slug: "private-1-1", label: "Private 1:1" },
      { slug: "semi-private-small-group", label: "Semi-private / small group" },
      { slug: "virtual-live-video", label: "Virtual live (video)" },
      { slug: "on-demand-recorded-content", label: "On-demand / recorded content" },
    ],
  },
  {
    key: "recurrence",
    label: "Recurrence",
    options: [
      { slug: "recurring-classes", label: "Recurring classes" },
      { slug: "rolling-enrollments", label: "Rolling enrollments" },
      { slug: "fixed-date-courses", label: "Fixed-date courses" },
      { slug: "waitlist-for-courses", label: "Waitlist for courses" },
    ],
  },
  {
    key: "capacity-and-time-controls",
    label: "Capacity & time controls",
    options: [
      { slug: "capacity-limit", label: "Capacity limit" },
      { slug: "equipment-based-capacity", label: "Equipment-based capacity" },
      { slug: "overbooking-allowance", label: "Overbooking allowance" },
      { slug: "waitlist", label: "Waitlist" },
      { slug: "auto-promotion-from-waitlist", label: "Auto-promotion from waitlist" },
      { slug: "booking-window-open-close", label: "Booking window (open/close)" },
      { slug: "cut-off-time-before-start", label: "Cut-off time before start" },
      { slug: "late-cancel-rules", label: "Late cancel rules" },
      { slug: "no-show-fee", label: "No-show fee" },
      { slug: "grace-periods", label: "Grace periods" },
      { slug: "buffer-times-between-classes", label: "Buffer times between classes" },
    ],
  },
  {
    key: "resource-allocation",
    label: "Resource allocation",
    options: [
      { slug: "rooms-locations", label: "Rooms / locations" },
      { slug: "equipment", label: "Equipment" },
      { slug: "instructors", label: "Instructors" },
      { slug: "multiple-resources-per-booking", label: "Multiple resources per booking" },
      { slug: "conflict-detection-prevention", label: "Conflict detection / prevention" },
    ],
  },
  {
    key: "calendar-sync",
    label: "Calendar sync",
    options: [
      { slug: "google-calendar-2-way", label: "Google Calendar (2-way)" },
      { slug: "outlook-2-way", label: "Outlook (2-way)" },
      { slug: "icloud-2-way", label: "iCloud (2-way)" },
      { slug: "ics-feed-1-way", label: "ICS feed (1-way)" },
    ],
  },
  {
    key: "check-in-and-access",
    label: "Check-in & access",
    options: [
      { slug: "staff-check-in", label: "Staff check-in" },
      { slug: "mobile-app-check-in", label: "Mobile app check-in" },
      { slug: "kiosk-ipad-check-in", label: "Kiosk / iPad check-in" },
      { slug: "qr-code-barcode-scanning", label: "QR code / barcode scanning" },
      { slug: "nfc-rfid", label: "NFC / RFID" },
      { slug: "turnstile-door-access-integration", label: "Turnstile / door access integration" },
    ],
  },
  {
    key: "forms-and-waivers",
    label: "Forms & waivers",
    options: [
      { slug: "custom-intake-forms", label: "Custom intake forms" },
      { slug: "conditional-logic", label: "Conditional logic" },
      { slug: "e-sign-waivers", label: "E-sign waivers" },
      { slug: "health-screening", label: "Health screening" },
      { slug: "parental-consent", label: "Parental consent" },
      { slug: "photo-video-consent", label: "Photo/video consent" },
      { slug: "per-class-forms", label: "Per-class forms" },
      { slug: "custom-fields", label: "Custom fields" },
    ],
  },
  {
    key: "booking-models",
    label: "Booking models",
    options: [
      { slug: "guest-checkout", label: "Guest checkout" },
      { slug: "account-required", label: "Account required" },
      { slug: "family-group-bookings", label: "Family / group bookings" },
      { slug: "corporate-team-bookings", label: "Corporate / team bookings" },
      { slug: "multi-attendee-in-one-booking", label: "Multi-attendee in one booking" },
      { slug: "add-on-upsells-at-checkout", label: "Add-on upsells at checkout" },
    ],
  },
  {
    key: "notifications",
    label: "Notifications",
    options: [
      { slug: "email-reminders", label: "Email reminders" },
      { slug: "sms-reminders", label: "SMS reminders" },
      { slug: "push-notifications", label: "Push notifications" },
      { slug: "whatsapp-notifications", label: "WhatsApp notifications" },
      { slug: "two-way-sms", label: "Two-way SMS" },
      { slug: "custom-templates", label: "Custom templates" },
      { slug: "automated-waitlist-messages", label: "Automated waitlist messages" },
    ],
  },
  {
    key: "payment-gateways",
    label: "Payment gateways",
    options: [
      { slug: "stripe", label: "Stripe" },
      { slug: "paypal", label: "PayPal" },
      { slug: "square", label: "Square" },
      { slug: "adyen", label: "Adyen" },
      { slug: "braintree", label: "Braintree" },
      { slug: "authorize-net", label: "Authorize.Net" },
      { slug: "worldpay", label: "Worldpay" },
      { slug: "mollie", label: "Mollie" },
      { slug: "razorpay", label: "Razorpay" },
      { slug: "paystack", label: "Paystack" },
      { slug: "payu", label: "PayU" },
      { slug: "mercado-pago", label: "Mercado Pago" },
      { slug: "2checkout", label: "2Checkout" },
      { slug: "checkout-com", label: "Checkout.com" },
      { slug: "klarna-payments", label: "Klarna Payments" },
    ],
  },
  {
    key: "payment-methods",
    label: "Payment methods",
    options: [
      { slug: "credit-debit-cards-visa-mastercard-amex-discover", label: "Credit/Debit cards (Visa/Mastercard/Amex/Discover)" },
      { slug: "apple-pay", label: "Apple Pay" },
      { slug: "google-pay", label: "Google Pay" },
      { slug: "buy-now-pay-later-afterpay-clearpay-klarna-affirm", label: "Buy Now Pay Later (Afterpay/Clearpay/Klarna/Affirm)" },
      { slug: "bank-transfer", label: "Bank transfer" },
      { slug: "sepa-direct-debit", label: "SEPA Direct Debit" },
      { slug: "ach-debit", label: "ACH Debit" },
      { slug: "ideal", label: "iDEAL" },
      { slug: "bancontact", label: "Bancontact" },
      { slug: "eps", label: "EPS" },
      { slug: "giropay", label: "giropay" },
      { slug: "przelewy24", label: "Przelewy24" },
      { slug: "pix", label: "PIX" },
      { slug: "boleto", label: "Boleto" },
      { slug: "paynow-sg", label: "PayNow (SG)" },
      { slug: "grabpay", label: "GrabPay" },
      { slug: "alipay", label: "Alipay" },
      { slug: "wechat-pay", label: "WeChat Pay" },
      { slug: "cash", label: "Cash" },
      { slug: "cheque", label: "Cheque" },
    ],
  },
  {
    key: "point-of-sale-in-person",
    label: "Point of sale (in-person)",
    options: [
      { slug: "card-reader", label: "Card reader" },
      { slug: "tap-to-pay-on-iphone-android", label: "Tap to Pay on iPhone/Android" },
      { slug: "cash-drawer", label: "Cash drawer" },
      { slug: "receipt-printer", label: "Receipt printer" },
      { slug: "barcode-scanner", label: "Barcode scanner" },
    ],
  },
  {
    key: "pricing-models",
    label: "Pricing models",
    options: [
      { slug: "single-class", label: "Single class" },
      { slug: "class-packs-punch-cards", label: "Class packs / punch cards" },
      { slug: "memberships-subscriptions", label: "Memberships / subscriptions" },
      { slug: "intro-offers", label: "Intro offers" },
      { slug: "free-trials", label: "Free trials" },
      { slug: "tiered-pricing", label: "Tiered pricing" },
      { slug: "pay-what-you-want", label: "Pay-what-you-want" },
      { slug: "sliding-scale", label: "Sliding scale" },
      { slug: "corporate-rates", label: "Corporate rates" },
      { slug: "student-senior-rates", label: "Student/Senior rates" },
    ],
  },
  {
    key: "billing-and-collections",
    label: "Billing & collections",
    options: [
      { slug: "recurring-billing", label: "Recurring billing" },
      { slug: "proration", label: "Proration" },
      { slug: "dunning-retry-logic", label: "Dunning / retry logic" },
      { slug: "partial-payments", label: "Partial payments" },
      { slug: "deposits", label: "Deposits" },
      { slug: "split-payments", label: "Split payments" },
      { slug: "installments", label: "Installments" },
    ],
  },
  {
    key: "taxes-and-invoicing",
    label: "Taxes & invoicing",
    options: [
      { slug: "vat-gst-hst", label: "VAT/GST/HST" },
      { slug: "multiple-tax-rates", label: "Multiple tax rates" },
      { slug: "tax-inclusive-exclusive", label: "Tax inclusive/exclusive" },
      { slug: "automatic-tax-calculation", label: "Automatic tax calculation" },
      { slug: "fiscal-receipts", label: "Fiscal receipts" },
      { slug: "quotes", label: "Quotes" },
      { slug: "invoices", label: "Invoices" },
      { slug: "credit-notes", label: "Credit notes" },
      { slug: "purchase-orders", label: "Purchase orders" },
    ],
  },
  {
    key: "discounts-and-credits",
    label: "Discounts & credits",
    options: [
      { slug: "coupon-codes", label: "Coupon codes" },
      { slug: "auto-discounts", label: "Auto-discounts" },
      { slug: "volume-discounts", label: "Volume discounts" },
      { slug: "referral-discounts", label: "Referral discounts" },
      { slug: "loyalty-points-redemption", label: "Loyalty points redemption" },
      { slug: "gift-cards", label: "Gift cards" },
      { slug: "store-credit", label: "Store credit" },
    ],
  },
  {
    key: "risk-and-compliance",
    label: "Risk & compliance",
    options: [
      { slug: "3-d-secure-sca", label: "3-D Secure / SCA" },
      { slug: "pci-dss-compliance", label: "PCI DSS compliance" },
      { slug: "avs-address-verification", label: "AVS / Address verification" },
      { slug: "chargeback-management", label: "Chargeback management" },
      { slug: "risk-scoring-fraud-checks", label: "Risk scoring / fraud checks" },
    ],
  },
  {
    key: "profiles",
    label: "Profiles",
    options: [
      { slug: "family-accounts", label: "Family accounts" },
      { slug: "corporate-accounts", label: "Corporate accounts" },
      { slug: "emergency-contacts", label: "Emergency contacts" },
      { slug: "medical-notes", label: "Medical notes" },
      { slug: "tags-segments", label: "Tags / segments" },
    ],
  },
  {
    key: "memberships",
    label: "Memberships",
    options: [
      { slug: "contract-terms", label: "Contract terms" },
      { slug: "freezes-holds", label: "Freezes / holds" },
      { slug: "carryover-rules", label: "Carryover rules" },
      { slug: "cancellation-policies", label: "Cancellation policies" },
      { slug: "usage-limits", label: "Usage limits" },
      { slug: "access-control-by-membership", label: "Access control by membership" },
    ],
  },
  {
    key: "passes",
    label: "Passes",
    options: [
      { slug: "class-packs", label: "Class packs" },
      { slug: "expiration-rules", label: "Expiration rules" },
      { slug: "shareable-passes", label: "Shareable passes" },
      { slug: "transfer-rules", label: "Transfer rules" },
    ],
  },
  {
    key: "loyalty-and-referral",
    label: "Loyalty & referral",
    options: [
      { slug: "points", label: "Points" },
      { slug: "tiers", label: "Tiers" },
      { slug: "referrals", label: "Referrals" },
      { slug: "rewards-catalog", label: "Rewards catalog" },
      { slug: "streaks-badges", label: "Streaks / badges" },
    ],
  },
  {
    key: "gift-cards",
    label: "Gift cards",
    options: [
      { slug: "digital-gift-cards", label: "Digital gift cards" },
      { slug: "physical-gift-cards", label: "Physical gift cards" },
      { slug: "balance-management", label: "Balance management" },
      { slug: "scheduled-delivery", label: "Scheduled delivery" },
    ],
  },
  {
    key: "community",
    label: "Community",
    options: [
      { slug: "forums-groups", label: "Forums / groups" },
      { slug: "leaderboards", label: "Leaderboards" },
      { slug: "challenges", label: "Challenges" },
    ],
  },
  {
    key: "admin-and-permissions",
    label: "Admin & permissions",
    options: [
      { slug: "role-based-permissions", label: "Role-based permissions" },
      { slug: "field-level-permissions", label: "Field-level permissions" },
      { slug: "audit-logs", label: "Audit logs" },
    ],
  },
  {
    key: "scheduling-and-availability",
    label: "Scheduling & availability",
    options: [
      { slug: "staff-scheduling", label: "Staff scheduling" },
      { slug: "availability-rules", label: "Availability rules" },
      { slug: "time-off", label: "Time-off" },
      { slug: "shift-swaps", label: "Shift swaps" },
    ],
  },
  {
    key: "compensation",
    label: "Compensation",
    options: [
      { slug: "payroll-export", label: "Payroll export" },
      { slug: "commission-structures", label: "Commission structures" },
      { slug: "tips", label: "Tips" },
      { slug: "tip-pools", label: "Tip pools" },
      { slug: "performance-dashboards", label: "Performance dashboards" },
    ],
  },
  {
    key: "crm-and-lead-management",
    label: "CRM & lead management",
    options: [
      { slug: "contact-crm", label: "Contact CRM" },
      { slug: "lead-capture-forms", label: "Lead capture forms" },
      { slug: "lead-pipeline-stages", label: "Lead pipeline / stages" },
    ],
  },
  {
    key: "campaigns",
    label: "Campaigns",
    options: [
      { slug: "email-marketing", label: "Email marketing" },
      { slug: "sms-marketing", label: "SMS marketing" },
      { slug: "marketing-automation", label: "Marketing automation" },
      { slug: "abandoned-booking-recovery", label: "Abandoned booking recovery" },
      { slug: "promo-codes", label: "Promo codes" },
      { slug: "landing-pages", label: "Landing pages" },
      { slug: "seo-tools", label: "SEO tools" },
    ],
  },
  {
    key: "ads-and-tracking",
    label: "Ads & tracking",
    options: [
      { slug: "facebook-ads-pixel", label: "Facebook Ads pixel" },
      { slug: "google-ads-conversion", label: "Google Ads conversion" },
    ],
  },
];
